FROM ubuntu:bionic

# AWS APT mirrors
RUN sed -i 's+http://security.ubuntu.com/+http://archive.ubuntu.com/+g' /etc/apt/sources.list \
 && sed -i 's+http://archive.ubuntu.com/+http://us-east-1.ec2.archive.ubuntu.com/+g' /etc/apt/sources.list \
 && apt update \
 && rm -rf /var/lib/apt/lists/*

# Set timezone
RUN echo "America/Detroit" > /etc/timezone \
 && apt update \
 && apt install -y tzdata \
 && rm /etc/localtime \
 && ln -snf /usr/share/zoneinfo/`cat /etc/timezone` /etc/localtime \
 && dpkg-reconfigure -f noninteractive tzdata \
 && rm -rf /var/lib/apt/lists/*

# Install git and ssh
RUN apt update \
 && apt install -y git ssh-client \
 && rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN apt update \
 && apt install -y --no-install-recommends curl make \
 && rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN dpkg --add-architecture i386 \
 && apt update \
 && apt install -y --no-install-recommends curl libc6:i386 \
        libx11-6:i386 libxext6:i386 libstdc++6:i386 libexpat1:i386 \
        libxext6 libxrender1 libxtst6 libgtk2.0-0 make unzip \
 && rm -rf /var/lib/apt/lists/*

# Install python modules
RUN apt update \
 && apt install -y python-pip python-setuptools \
 && rm -rf /var/lib/apt/lists/* \
 && pip install --upgrade pip
RUN pip install glob2

# Add useful script for cleaning up after Microchip installs
RUN ADD microchip-remove-unused /usr/bin


# Download and install XC32 compiler
RUN curl -fSL -A "Mozilla/4.0" -o /tmp/xc32.run "http://ww1.microchip.com/downloads/en/DeviceDoc/xc32-v4.00-full-install-linux-installer.run" \
 && chmod a+x /tmp/xc32.run \
 && /tmp/xc32.run --mode unattended --unattendedmodeui none \
    --netservername localhost --LicenseType FreeMode \
 && rm /tmp/xc32.run
ENV PATH /opt/microchip/xc32/`ls /opt/microchip/xc32/ | awk '{print $1}'`/bin:$PATH


# Download and install MPLAB X IDE
# Use url: http://www.microchip.com/mplabx-ide-linux-installer to get the latest version
RUN curl -fSL -A "Mozilla/4.0" -o /tmp/mplabx-installer.tar "http://ww1.microchip.com/downloads/en/DeviceDoc/MPLABX-v6.00-linux-installer.tar" \
 && tar xf /tmp/mplabx-installer.tar && rm /tmp/mplabx-installer.tar \
 && USER=root ./*-installer.sh --nox11 \
    -- --unattendedmodeui none --mode unattended \
 && rm ./*-installer.sh


# Add MPLABX build scripts
RUN ln -s /usr/bin/mplabxBuildAll.py /usr/bin/mplabx-build-all
RUN ln -s /usr/bin/mplabxBuildProject.py /usr/bin/mplabx-build-project
 






