/**
 * @file    figarofit_export.h
 *
 * @brief   Compatibility header to replace autogenerated cmake one for use with
 *          xc32 compiler
 *
 * @attention
 * (c) Copyright Schlumberger Technology Corp., unpublished work,
 * created 2022.  This computer program includes confidential,
 * proprietary information and is a trade secret of Schlumberger
 * Technology Corp.  All use, disclosure, and/or reproduction is
 * prohibited unless authorized in writing.  All Rights Reserved.
 */
// *******************************************************************************

#ifndef _FIGAROFIT_EXPORT_H    /* Guard against multiple inclusion */
#define _FIGAROFIT_EXPORT_H


#ifdef __cplusplus
extern "C" {
#endif

#define FIGAROFIT_EXPORT 


    /* Provide C++ Compatibility */
#ifdef __cplusplus
}
#endif

#endif 